#!/bin/sh

SHELL=/bin/sh
PATH=/sbin:/bin:/usr/sbin:/usr/bin

ansible-pull -i /etc/ansible/hosts --vault-password-file /etc/ansible/vaultpass -d {{ pull_mode_workdir }} -U {{ pull_mode_repo_url }} -s {{ pull_mode_random_sleep }} >> {{ pull_mode_logfile }} 2>&1
